import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
import { VoiceToggle } from "@/features/VoiceControl/components/VoiceToggle";
import { VoiceNavigation } from "@/features/VoiceNavigation/VoiceNavigation";
import { VoiceControlInit } from "@/features/VoiceControl/VoiceControlInit";
import { VoiceLogger } from "@/features/VoiceLogger/VoiceLogger";
import { UserProvider } from "@/features/User/UserProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <VoiceControlInit>
          <VoiceLogger>
            <VoiceNavigation>
              {children}
              <VoiceToggle />
            </VoiceNavigation>
          </VoiceLogger>
        </VoiceControlInit>
        <Toaster />
      </body>
    </html>
  );
}
